### PR TITLE
Add verify scripts for various checks

### PR DESCRIPTION
**Pull request by yuanchen8911**
Add verification and check scripts: gofmt, golint, spelling check, yaml format, ...
`hack/verifiy-all`  or `make verify` will perform all checks.
`hack/update-all` or `make update` will correct all the issues.

### CODE REVIEW

**Comment by dmitsh** [comment]
isn't it an overkill?

**Comment by yuanchen8911** [comment]
> isn't it an overkill?

Up to you.

**Comment by shinae-woo** [comment]
I have one issue on yaml format, which I can ignore.

```
shinaew@shinae-sjc-desktop:~/src/knavigator$ make update
[*] Update go format...
Update go format
[*] Update go mod...
[*] Update go lint...
[*] Update ends newline...
[*] Update shell format...
Update shell format
[*] Update yaml format...
Update yaml format
2024/05/10 12:34:43 encountered the following formatting errors:
./charts/virtual-nodes/templates/nodes.yaml: yaml: line 3: did not find expected alphabetic or numeric character
exit status 1
[*] Update spelling...
Update failed for: yaml-format
make: *** [Makefile:33: update] Error 1
```

And two new lines at end of file

```
diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
index 86f894f..134ab8d 100644
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -60,4 +60,4 @@ jobs:
           context: .
           push: ${{ github.event_name != 'pull_request' }}
           tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
\ No newline at end of file
+          labels: ${{ steps.meta.outputs.labels }}
diff --git a/docs/task_management.md b/docs/task_management.md
index fb84593..d24157f 100644
--- a/docs/task_management.md
+++ b/docs/task_management.md
@@ -8,4 +8,4 @@ Tasks are defined in a YAML format or received via HTTP/gRPC protocols. The Task
 - Check the spec and status of nodes
 - Check the spec and status of pods
 - Run PromQL query
-- Sleep for a specified duration
\ No newline at end of file
+- Sleep for a specified duration
```

**Review by shinae-woo — APPROVED** [review]
LGTM other than issues I reported on above comments

**Comment by yuanchen8911** [comment]
> LGTM other than issues I reported on above comments

Thanks! Not sure how to fix the first one.  https://github.com/NVIDIA/knavigator/pull/28 should fix the empty line issues.

**Pull request merged**
